Toolchain version 1.59.0.0 (#41)
* ci: shallow clone
* ci: self-hosted aarch64 linux build
* ci: use self-hosted runners for all builds
* ci: new style of image with Rust + ESP-IDF

diff --git a/.github/workflows/build-rust-aarch64-apple-darwin-self-hosted-dispatch.yaml b/.github/workflows/build-rust-aarch64-apple-darwin-self-hosted-dispatch.yaml
--- a/.github/workflows/build-rust-aarch64-apple-darwin-self-hosted-dispatch.yaml
+++ b/.github/workflows/build-rust-aarch64-apple-darwin-self-hosted-dispatch.yaml
@@ -2,7 +2,28 @@
 name: build-rust-macos-m1-dispatch
 
 on:
-  workflow_dispatch
+  workflow_dispatch:
+    inputs:
+      upload_artifacts:
+        description: 'Upload final artifacts to Release?'
+        required: true
+        default: 'no'
+      rust_build_branch:
+        description: 'Branch of rust-build to use'
+        required: true
+        default: 'main'
+      release_version:
+        description: 'Release Version for generation'
+        required: true
+        default: '1.59.0.0'
+      rust_version:
+        description: 'Version of esp rust to use'
+        required: true
+        default: '1.59.0'
+      rust_target:
+        description: 'Target triple'
+        required: true
+        default: 'aarch64-apple-darwin'
 
 jobs:
   get_release:
@@ -38,41 +59,23 @@ jobs:
         os: [ macos-m1-self-hosted ]
         include:
         - os: macos-m1-self-hosted
-          ARCH: ''
-          TARGET: win-x64
-          ASSET_PATH: 'build/dist/rust-1.58.0-dev-aarch64-apple-darwin.tar.xz'
-          ASSET_NAME: 'rust-1.58.0.0-aarch64-apple-darwin.tar.xz'
+          ASSET_PATH: 'build/dist/rust-${{ github.event.inputs.rust_version }}-dev-${{ github.event.inputs.rust_target }}.tar.xz'
+          ASSET_NAME: 'rust-${{ github.event.inputs.release_version }}-${{ github.event.inputs.rust_target }}.tar.xz'
           ASSET_CONTENT_TYPE: 'application/x-tar'
-          LLVM_ROOT_OPTION: ''
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
         with:
           repository: esp-rs/rust
-          ref: esp-1.58.0.0
+          ref: esp-${{ github.event.inputs.release_version }}
           submodules: true
-      - name: Set up Python
-        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-18.04' || matrix.os == 'windows-latest' }}
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.8'
-      - name: Setup Ninja
-        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-18.04' || matrix.os == 'windows-latest' }}
-        uses: seanmiddleditch/gha-setup-ninja@master
       - name: Prepare build
         run: |
-          arch -arm64 python3 src/bootstrap/configure.py ${{ matrix.LLVM_ROOT_OPTION }} --experimental-targets=Xtensa --enable-extended --tools=clippy,cargo,rustfmt --dist-compression-formats='xz' --set rust.jemalloc
-      - name: Build with x.py - dist packages
-        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-18.04' }}
-        # ignore build failure - workaround for pkgbuild problems
-        run: |
-          python3 x.py dist --stage 2  || echo "build finished"
-        # Excluding src/doc breaks build of 1.55
-        #run: python3 x.py dist --stage 2 --exclude src/doc
+          arch -arm64 python3 src/bootstrap/configure.py --experimental-targets=Xtensa --enable-extended --tools=clippy,cargo,rustfmt --dist-compression-formats='xz' --set rust.jemalloc
       - name: Build with x.py - dist packages - with cached LLVM
-        if: ${{ matrix.os == 'macos-m1-self-hosted' }}
-        run: arch -arm64 python3 x.py dist --stage 2 --llvm-skip-rebuild TRUE
+        run: arch -arm64 python3 x.py dist --stage 2 || echo "silence pkg build error"
       - name: Upload Release Asset
+        if: github.event.inputs.upload_artifacts == 'yes'
         id: upload-release-asset
         uses: actions/upload-release-asset@v1
         env:
diff --git a/.github/workflows/build-rust-x86_64-apple-darwin-self-hosted-dispatch.yaml b/.github/workflows/build-rust-x86_64-apple-darwin-self-hosted-dispatch.yaml
--- a/.github/workflows/build-rust-x86_64-apple-darwin-self-hosted-dispatch.yaml
+++ b/.github/workflows/build-rust-x86_64-apple-darwin-self-hosted-dispatch.yaml
@@ -2,7 +2,28 @@
 name: build-rust-macos-x86_64-self-hosted-dispatch
 
 on:
-  workflow_dispatch
+  workflow_dispatch:
+    inputs:
+      upload_artifacts:
+        description: 'Upload final artifacts to Release?'
+        required: true
+        default: 'no'
+      rust_build_branch:
+        description: 'Branch of rust-build to use'
+        required: true
+        default: 'main'
+      release_version:
+        description: 'Release Version for generation'
+        required: true
+        default: '1.59.0.0'
+      rust_version:
+        description: 'Version of esp rust to use'
+        required: true
+        default: '1.59.0'
+      rust_target:
+        description: 'Target triple'
+        required: true
+        default: 'x86_64-apple-darwin'
 
 jobs:
   get_release:
@@ -27,3 +48,40 @@ jobs:
         echo "::set-output name=url::$url"
       env:
         response:  ${{ steps.get_latest_release.outputs.data }}
+
+  build-idf-rust:
+    name: Build IDF Rust for ${{ matrix.os }}
+    # needs: create_release
+    needs: get_release
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ macos-x86_64-self-hosted ]
+        include:
+        - os: macos-x86_64-self-hosted
+          ASSET_PATH: 'build/dist/rust-${{ github.event.inputs.rust_version }}-dev-${{ github.event.inputs.rust_target }}.tar.xz'
+          ASSET_NAME: 'rust-${{ github.event.inputs.release_version }}-${{ github.event.inputs.rust_target }}.tar.xz'
+          ASSET_CONTENT_TYPE: 'application/x-tar'
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+        with:
+          repository: esp-rs/rust
+          ref: esp-${{ github.event.inputs.release_version }}
+          submodules: true
+      - name: Prepare build
+        run: |
+          python3 src/bootstrap/configure.py --experimental-targets=Xtensa --enable-extended --tools=clippy,cargo,rustfmt --dist-compression-formats='xz' --set rust.jemalloc
+      - name: Build with x.py - dist packages
+        run: python3 x.py dist --stage 2 || echo "Ignoring pkg failure"
+      - name: Upload Release Asset
+        if: github.event.inputs.upload_artifacts == 'yes'
+        id: upload-release-asset
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ needs.get_release.outputs.upload_url }}
+          asset_path: ${{ matrix.ASSET_PATH }}
+          asset_name: ${{ matrix.ASSET_NAME }}
+          asset_content_type: ${{ matrix.ASSET_CONTENT_TYPE }}
