Build/1.57 (#22)
* Workflow changes for running on native github runners (#19)
* Added composite actions
* Added workflow for building the source tar.xz
* updates to top level workflows
* fix for creation of the archive
* Feature/binary tools (#18)
* tools: use cargo-espflash from binary when possible
* build: change versioning schema of esp-rs/rust repo to full version number
* build: add clippy
* ci: change order of std/rusc add jemalloc
* ci: update self hosted macOS
* ci: force build architecture for aarch64
* ci: add option to specify llvm-version
* ci: llvm version specification support for PowerShell
* ci: upgrade to LLVM13
* tool: add support for aarch64-unknown-linux-gnu installation

Co-authored-by: Hecatron <hecatrons.workshop@gmail.com>

diff --git a/.github/workflows/build-rust-aarch64-apple-darwin-dispatch.yaml b/.github/workflows/build-rust-aarch64-apple-darwin-dispatch.yaml
--- a/.github/workflows/build-rust-aarch64-apple-darwin-dispatch.yaml
+++ b/.github/workflows/build-rust-aarch64-apple-darwin-dispatch.yaml
@@ -40,8 +40,8 @@ jobs:
         - os: macos-m1-self-hosted
           ARCH: ''
           TARGET: win-x64
-          ASSET_PATH: 'build/dist/rust-1.56.0-dev-aarch64-apple-darwin.tar.xz'
-          ASSET_NAME: 'rust-1.56.0.1-dev-aarch64-apple-darwin.tar.xz'
+          ASSET_PATH: 'build/dist/rust-1.57.0-dev-aarch64-apple-darwin.tar.xz'
+          ASSET_NAME: 'rust-1.57.0.2-aarch64-apple-darwin.tar.xz'
           ASSET_CONTENT_TYPE: 'application/x-tar'
           LLVM_ROOT_OPTION: ''
     steps:
@@ -49,7 +49,7 @@ jobs:
         uses: actions/checkout@v2
         with:
           repository: esp-rs/rust
-          ref: esp-1.56.0
+          ref: esp-1.57.0.2
           submodules: true
       - name: Set up Python
         if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-18.04' || matrix.os == 'windows-latest' }}
@@ -60,15 +60,18 @@ jobs:
         if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-18.04' || matrix.os == 'windows-latest' }}
         uses: seanmiddleditch/gha-setup-ninja@master
       - name: Prepare build
-        run: python3 src/bootstrap/configure.py ${{ matrix.LLVM_ROOT_OPTION }} --experimental-targets=Xtensa --enable-extended --tools=rustfmt --dist-compression-formats='xz'
+        run: |
+          arch -arm64 python3 src/bootstrap/configure.py ${{ matrix.LLVM_ROOT_OPTION }} --experimental-targets=Xtensa --enable-extended --tools=clippy,cargo,rustfmt --dist-compression-formats='xz' --set rust.jemalloc
       - name: Build with x.py - dist packages
         if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-18.04' }}
-        run: python3 x.py dist --stage 2
+        # ignore build failure - workaround for pkgbuild problems
+        run: |
+          python3 x.py dist --stage 2  || echo "build finished"
         # Excluding src/doc breaks build of 1.55
         #run: python3 x.py dist --stage 2 --exclude src/doc
       - name: Build with x.py - dist packages - with cached LLVM
         if: ${{ matrix.os == 'macos-m1-self-hosted' }}
-        run: python3 x.py dist --stage 2 --llvm-skip-rebuild TRUE
+        run: arch -arm64 python3 x.py dist --stage 2 --llvm-skip-rebuild TRUE
       - name: Upload Release Asset
         id: upload-release-asset
         uses: actions/upload-release-asset@v1
